project_id = "xlgzxmzejlshsgeiidsz"

[functions.change-subscription]
verify_jwt = false

[functions.callhippo]
verify_jwt = true

[functions.contracts]
verify_jwt = false

[functions.process-commissions]
verify_jwt = true

[functions.pay-commission]
verify_jwt = true

[functions.unlock-workspace]
verify_jwt = true

[functions.send-commission-email]
verify_jwt = true

[functions.create-notification]
verify_jwt = true

[functions.create-commission]
verify_jwt = true

[functions.process-overdue-commissions]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = true

[functions.verify-email]
verify_jwt = false

[functions.twilio]
verify_jwt = true

[functions.twilio-webhook]
verify_jwt = false

[functions.assign-role]
verify_jwt = true

[functions.reset-free-minutes]
verify_jwt = false

[functions.purchase-dialer-credits]
verify_jwt = true

[functions.provision-phone-number]
verify_jwt = true

[functions.release-phone-number]
verify_jwt = true

[functions.video-token]
verify_jwt = true

[functions.send-contract-email]
verify_jwt = true
